name: flake8
on: pull_request
jobs:
  flake8:
    name: check code with Flake8
    runs-on: ubuntu-20.04
    container: fedora:32
    steps:
        - name: install Pipenv and Git
        run: dnf install -y pipenv git
        - name: checkout code
        uses: actions/checkout@v2
        - name: Setup enviornment
        run: pipenv sync --dev
        - name: Run Flake8
        run: pipenv run flake8 --max-line-length 120
		